//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workaholic.RTFEditor.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RTFEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RTFEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workaholic.RTFEditor.Test.RTFEditor", typeof(RTFEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Keys similar to B, Control.
        /// </summary>
        public static System.Windows.Forms.Keys boldToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("boldToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=167, Height=22}.
        /// </summary>
        public static System.Drawing.Size boldToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("boldToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bold.
        /// </summary>
        public static string boldToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("boldToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=167, Height=22}.
        /// </summary>
        public static System.Drawing.Size centerToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("centerToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Center.
        /// </summary>
        public static string centerToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("centerToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Keys similar to C, Control.
        /// </summary>
        public static System.Windows.Forms.Keys copyToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("copyToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=144, Height=22}.
        /// </summary>
        public static System.Drawing.Size copyToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("copyToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string copyToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("copyToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Keys similar to X, Control.
        /// </summary>
        public static System.Windows.Forms.Keys cutToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("cutToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=144, Height=22}.
        /// </summary>
        public static System.Drawing.Size cutToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("cutToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ut.
        /// </summary>
        public static string cutToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("cutToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=20}.
        /// </summary>
        public static System.Drawing.Size editToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("editToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string editToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("editToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=37, Height=20}.
        /// </summary>
        public static System.Drawing.Size fileToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("fileToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string fileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=57, Height=20}.
        /// </summary>
        public static System.Drawing.Size formatToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("formatToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F&amp;ormat.
        /// </summary>
        public static string formatToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("formatToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Keys similar to I, Control.
        /// </summary>
        public static System.Windows.Forms.Keys italicToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("italicToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=167, Height=22}.
        /// </summary>
        public static System.Drawing.Size italicToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("italicToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Italic.
        /// </summary>
        public static string italicToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("italicToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=167, Height=22}.
        /// </summary>
        public static System.Drawing.Size leftToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("leftToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&amp;eft.
        /// </summary>
        public static string leftToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("leftToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to None.
        /// </summary>
        public static System.Windows.Forms.DockStyle ms_Dock {
            get {
                object obj = ResourceManager.GetObject("ms.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point ms_Location {
            get {
                object obj = ResourceManager.GetObject("ms.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=730, Height=24}.
        /// </summary>
        public static System.Drawing.Size ms_Size {
            get {
                object obj = ResourceManager.GetObject("ms.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int ms_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ms.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point ms_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("ms.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Keys similar to N, Control.
        /// </summary>
        public static System.Windows.Forms.Keys newToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("newToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=146, Height=22}.
        /// </summary>
        public static System.Drawing.Size newToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("newToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        public static string newToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("newToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Black].
        /// </summary>
        public static System.Drawing.Color openToolStripMenuItem_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("openToolStripMenuItem.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Keys similar to O, Control.
        /// </summary>
        public static System.Windows.Forms.Keys openToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("openToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=146, Height=22}.
        /// </summary>
        public static System.Drawing.Size openToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("openToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        public static string openToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("openToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Keys similar to V, Control.
        /// </summary>
        public static System.Windows.Forms.Keys pasteToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("pasteToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=144, Height=22}.
        /// </summary>
        public static System.Drawing.Size pasteToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("pasteToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        public static string pasteToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("pasteToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Keys similar to Y, Control.
        /// </summary>
        public static System.Windows.Forms.Keys redoToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("redoToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=144, Height=22}.
        /// </summary>
        public static System.Drawing.Size redoToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("redoToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        public static string redoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("redoToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=167, Height=22}.
        /// </summary>
        public static System.Drawing.Size rightToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("rightToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Right.
        /// </summary>
        public static string rightToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("rightToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle rtb_Dock {
            get {
                object obj = ResourceManager.GetObject("rtb.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point rtb_Location {
            get {
                object obj = ResourceManager.GetObject("rtb.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=730, Height=45}.
        /// </summary>
        public static System.Drawing.Size rtb_Size {
            get {
                object obj = ResourceManager.GetObject("rtb.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int rtb_TabIndex {
            get {
                object obj = ResourceManager.GetObject("rtb.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string rtb_Text {
            get {
                return ResourceManager.GetString("rtb.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Keys similar to S, Control.
        /// </summary>
        public static System.Windows.Forms.Keys saveToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("saveToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=146, Height=22}.
        /// </summary>
        public static System.Drawing.Size saveToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("saveToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string saveToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=167, Height=22}.
        /// </summary>
        public static System.Drawing.Size selectfontToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("selectfontToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;font.
        /// </summary>
        public static string selectfontToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("selectfontToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Keys similar to T, Control.
        /// </summary>
        public static System.Windows.Forms.Keys strikeoutToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("strikeoutToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=167, Height=22}.
        /// </summary>
        public static System.Drawing.Size strikeoutToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("strikeoutToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;trikeout.
        /// </summary>
        public static string strikeoutToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("strikeoutToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=730, Height=45}.
        /// </summary>
        public static System.Drawing.Size toolStripContainer1_ContentPanel_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripContainer1.ContentPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle toolStripContainer1_Dock {
            get {
                object obj = ResourceManager.GetObject("toolStripContainer1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point toolStripContainer1_Location {
            get {
                object obj = ResourceManager.GetObject("toolStripContainer1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=730, Height=96}.
        /// </summary>
        public static System.Drawing.Size toolStripContainer1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripContainer1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int toolStripContainer1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("toolStripContainer1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolStripContainer1.
        /// </summary>
        public static string toolStripContainer1_Text {
            get {
                return ResourceManager.GetString("toolStripContainer1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=27}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=27}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator2_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=27}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator3_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=27}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator4_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=27}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator5_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=27}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator6_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator6.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=141, Height=6}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator7_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator7.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=164, Height=6}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator8_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator8.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=164, Height=6}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator9_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator9.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to None.
        /// </summary>
        public static System.Windows.Forms.DockStyle ts_Dock {
            get {
                object obj = ResourceManager.GetObject("ts.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=24}.
        /// </summary>
        public static System.Drawing.Point ts_Location {
            get {
                object obj = ResourceManager.GetObject("ts.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=721, Height=27}.
        /// </summary>
        public static System.Drawing.Size ts_Size {
            get {
                object obj = ResourceManager.GetObject("ts.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int ts_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ts.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=24}.
        /// </summary>
        public static System.Drawing.Point ts_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("ts.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsBackgroundColor_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBackgroundColor.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=33, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsBackgroundColor_Size {
            get {
                object obj = ResourceManager.GetObject("tsBackgroundColor.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     .
        /// </summary>
        public static string tsBackgroundColor_Text {
            get {
                return ResourceManager.GetString("tsBackgroundColor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string tsBackgroundColor_ToolTipText {
            get {
                return ResourceManager.GetString("tsBackgroundColor.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsBold_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBold.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsBold_Size {
            get {
                object obj = ResourceManager.GetObject("tsBold.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string tsBold_Text {
            get {
                return ResourceManager.GetString("tsBold.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsBullet_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBullet.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Transparent].
        /// </summary>
        public static System.Drawing.Color tsBullet_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsBullet.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsBullet_Size {
            get {
                object obj = ResourceManager.GetObject("tsBullet.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet.
        /// </summary>
        public static string tsBullet_Text {
            get {
                return ResourceManager.GetString("tsBullet.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsCenter_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsCenter.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsCenter_Size {
            get {
                object obj = ResourceManager.GetObject("tsCenter.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string tsCenter_Text {
            get {
                return ResourceManager.GetString("tsCenter.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsCopy_Image {
            get {
                object obj = ResourceManager.GetObject("tsCopy.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsCopy_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsCopy.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Transparent].
        /// </summary>
        public static System.Drawing.Color tsCopy_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsCopy.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsCopy_Size {
            get {
                object obj = ResourceManager.GetObject("tsCopy.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string tsCopy_Text {
            get {
                return ResourceManager.GetString("tsCopy.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsCut_Image {
            get {
                object obj = ResourceManager.GetObject("tsCut.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsCut_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsCut.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Transparent].
        /// </summary>
        public static System.Drawing.Color tsCut_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsCut.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsCut_Size {
            get {
                object obj = ResourceManager.GetObject("tsCut.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string tsCut_Text {
            get {
                return ResourceManager.GetString("tsCut.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=27}.
        /// </summary>
        public static System.Drawing.Size tsFileSeparator_Size {
            get {
                object obj = ResourceManager.GetObject("tsFileSeparator.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsFontColor_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsFontColor.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=33, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsFontColor_Size {
            get {
                object obj = ResourceManager.GetObject("tsFontColor.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     .
        /// </summary>
        public static string tsFontColor_Text {
            get {
                return ResourceManager.GetString("tsFontColor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font color  .
        /// </summary>
        public static string tsFontColor_ToolTipText {
            get {
                return ResourceManager.GetString("tsFontColor.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool tsFontSize_AutoSize {
            get {
                object obj = ResourceManager.GetObject("tsFontSize.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string tsFontSize_Items {
            get {
                return ResourceManager.GetString("tsFontSize.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string tsFontSize_Items1 {
            get {
                return ResourceManager.GetString("tsFontSize.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        public static string tsFontSize_Items10 {
            get {
                return ResourceManager.GetString("tsFontSize.Items10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        public static string tsFontSize_Items11 {
            get {
                return ResourceManager.GetString("tsFontSize.Items11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        public static string tsFontSize_Items12 {
            get {
                return ResourceManager.GetString("tsFontSize.Items12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        public static string tsFontSize_Items13 {
            get {
                return ResourceManager.GetString("tsFontSize.Items13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48.
        /// </summary>
        public static string tsFontSize_Items14 {
            get {
                return ResourceManager.GetString("tsFontSize.Items14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 72.
        /// </summary>
        public static string tsFontSize_Items15 {
            get {
                return ResourceManager.GetString("tsFontSize.Items15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string tsFontSize_Items2 {
            get {
                return ResourceManager.GetString("tsFontSize.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string tsFontSize_Items3 {
            get {
                return ResourceManager.GetString("tsFontSize.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string tsFontSize_Items4 {
            get {
                return ResourceManager.GetString("tsFontSize.Items4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string tsFontSize_Items5 {
            get {
                return ResourceManager.GetString("tsFontSize.Items5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        public static string tsFontSize_Items6 {
            get {
                return ResourceManager.GetString("tsFontSize.Items6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        public static string tsFontSize_Items7 {
            get {
                return ResourceManager.GetString("tsFontSize.Items7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string tsFontSize_Items8 {
            get {
                return ResourceManager.GetString("tsFontSize.Items8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string tsFontSize_Items9 {
            get {
                return ResourceManager.GetString("tsFontSize.Items9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=50, Height=23}.
        /// </summary>
        public static System.Drawing.Size tsFontSize_Size {
            get {
                object obj = ResourceManager.GetObject("tsFontSize.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string tsFontSize_ToolTipText {
            get {
                return ResourceManager.GetString("tsFontSize.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=61, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsFontType_Size {
            get {
                object obj = ResourceManager.GetObject("tsFontType.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font type.
        /// </summary>
        public static string tsFontType_Text {
            get {
                return ResourceManager.GetString("tsFontType.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsIdentMinus_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsIdentMinus.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Transparent].
        /// </summary>
        public static System.Drawing.Color tsIdentMinus_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsIdentMinus.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsIdentMinus_Size {
            get {
                object obj = ResourceManager.GetObject("tsIdentMinus.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ident minus.
        /// </summary>
        public static string tsIdentMinus_Text {
            get {
                return ResourceManager.GetString("tsIdentMinus.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsIdentPlus_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsIdentPlus.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Transparent].
        /// </summary>
        public static System.Drawing.Color tsIdentPlus_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsIdentPlus.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsIdentPlus_Size {
            get {
                object obj = ResourceManager.GetObject("tsIdentPlus.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ident plus.
        /// </summary>
        public static string tsIdentPlus_Text {
            get {
                return ResourceManager.GetString("tsIdentPlus.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsItalic_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsItalic.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsItalic_Size {
            get {
                object obj = ResourceManager.GetObject("tsItalic.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string tsItalic_Text {
            get {
                return ResourceManager.GetString("tsItalic.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsLeft_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsLeft.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsLeft_Size {
            get {
                object obj = ResourceManager.GetObject("tsLeft.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string tsLeft_Text {
            get {
                return ResourceManager.GetString("tsLeft.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsNew_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsNew.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Transparent].
        /// </summary>
        public static System.Drawing.Color tsNew_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsNew.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsNew_Size {
            get {
                object obj = ResourceManager.GetObject("tsNew.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string tsNew_Text {
            get {
                return ResourceManager.GetString("tsNew.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsOpen_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsOpen.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Black].
        /// </summary>
        public static System.Drawing.Color tsOpen_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsOpen.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=23, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsOpen_Size {
            get {
                object obj = ResourceManager.GetObject("tsOpen.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string tsOpen_Text {
            get {
                return ResourceManager.GetString("tsOpen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsPaste_Image {
            get {
                object obj = ResourceManager.GetObject("tsPaste.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsPaste_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsPaste.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Transparent].
        /// </summary>
        public static System.Drawing.Color tsPaste_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsPaste.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsPaste_Size {
            get {
                object obj = ResourceManager.GetObject("tsPaste.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string tsPaste_Text {
            get {
                return ResourceManager.GetString("tsPaste.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsRedo_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsRedo.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Transparent].
        /// </summary>
        public static System.Drawing.Color tsRedo_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsRedo.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsRedo_Size {
            get {
                object obj = ResourceManager.GetObject("tsRedo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string tsRedo_Text {
            get {
                return ResourceManager.GetString("tsRedo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsRight_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsRight.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsRight_Size {
            get {
                object obj = ResourceManager.GetObject("tsRight.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string tsRight_Text {
            get {
                return ResourceManager.GetString("tsRight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsSave_Image {
            get {
                object obj = ResourceManager.GetObject("tsSave.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsSave_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsSave.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Transparent].
        /// </summary>
        public static System.Drawing.Color tsSave_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsSave.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsSave_Size {
            get {
                object obj = ResourceManager.GetObject("tsSave.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string tsSave_Text {
            get {
                return ResourceManager.GetString("tsSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=144, Height=22}.
        /// </summary>
        public static System.Drawing.Size tsSelectBackgroundColor_Size {
            get {
                object obj = ResourceManager.GetObject("tsSelectBackgroundColor.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select color....
        /// </summary>
        public static string tsSelectBackgroundColor_Text {
            get {
                return ResourceManager.GetString("tsSelectBackgroundColor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=144, Height=22}.
        /// </summary>
        public static System.Drawing.Size tsSelectFontColor_Size {
            get {
                object obj = ResourceManager.GetObject("tsSelectFontColor.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select color....
        /// </summary>
        public static string tsSelectFontColor_Text {
            get {
                return ResourceManager.GetString("tsSelectFontColor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsStrikeout_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsStrikeout.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsStrikeout_Size {
            get {
                object obj = ResourceManager.GetObject("tsStrikeout.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikeout.
        /// </summary>
        public static string tsStrikeout_Text {
            get {
                return ResourceManager.GetString("tsStrikeout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsUnderline_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsUnderline.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsUnderline_Size {
            get {
                object obj = ResourceManager.GetObject("tsUnderline.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string tsUnderline_Text {
            get {
                return ResourceManager.GetString("tsUnderline.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        public static System.Windows.Forms.ToolStripItemImageScaling tsUndo_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsUndo.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Transparent].
        /// </summary>
        public static System.Drawing.Color tsUndo_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsUndo.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=24}.
        /// </summary>
        public static System.Drawing.Size tsUndo_Size {
            get {
                object obj = ResourceManager.GetObject("tsUndo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string tsUndo_Text {
            get {
                return ResourceManager.GetString("tsUndo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool tsZoom_AutoSize {
            get {
                object obj = ResourceManager.GetObject("tsZoom.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400%.
        /// </summary>
        public static string tsZoom_Items {
            get {
                return ResourceManager.GetString("tsZoom.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300%.
        /// </summary>
        public static string tsZoom_Items1 {
            get {
                return ResourceManager.GetString("tsZoom.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200%.
        /// </summary>
        public static string tsZoom_Items2 {
            get {
                return ResourceManager.GetString("tsZoom.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150%.
        /// </summary>
        public static string tsZoom_Items3 {
            get {
                return ResourceManager.GetString("tsZoom.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        public static string tsZoom_Items4 {
            get {
                return ResourceManager.GetString("tsZoom.Items4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75%.
        /// </summary>
        public static string tsZoom_Items5 {
            get {
                return ResourceManager.GetString("tsZoom.Items5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50%.
        /// </summary>
        public static string tsZoom_Items6 {
            get {
                return ResourceManager.GetString("tsZoom.Items6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25%.
        /// </summary>
        public static string tsZoom_Items7 {
            get {
                return ResourceManager.GetString("tsZoom.Items7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=55, Height=23}.
        /// </summary>
        public static System.Drawing.Size tsZoom_Size {
            get {
                object obj = ResourceManager.GetObject("tsZoom.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Keys similar to U, Control.
        /// </summary>
        public static System.Windows.Forms.Keys underlineToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("underlineToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=167, Height=22}.
        /// </summary>
        public static System.Drawing.Size underlineToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("underlineToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Underline.
        /// </summary>
        public static string underlineToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("underlineToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Keys similar to Z, Control.
        /// </summary>
        public static System.Windows.Forms.Keys undoToolStripMenuItem_ShortcutKeys {
            get {
                object obj = ResourceManager.GetObject("undoToolStripMenuItem.ShortcutKeys", resourceCulture);
                return ((System.Windows.Forms.Keys)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=144, Height=22}.
        /// </summary>
        public static System.Drawing.Size undoToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("undoToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        public static string undoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("undoToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
